# Generated by Django 5.0.7 on 2024-08-23 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('소셜링', '소셜링'), ('나눔', '나눔')], max_length=10)),
                ('detail', models.CharField(choices=[('스터디', '스터디'), ('문화', '문화'), ('취미', '취미'), ('여행', '여행'), ('음식', '음식'), ('생활용품', '생활용품'), ('음식', '음식'), ('가구', '가구')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('limit', models.IntegerField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
