# Generated by Django 5.0.7 on 2024-08-23 17:20

import auths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutsaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nickname', models.CharField(max_length=64, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=64)),
                ('is_admin', models.BooleanField(default=False)),
                ('refresh_token', models.CharField(blank=True, max_length=256)),
                ('email', models.EmailField(blank=True, max_length=64)),
                ('school', models.CharField(blank=True, max_length=64)),
                ('home', models.CharField(blank=True, max_length=64)),
                ('region_1depth_name', models.CharField(blank=True, max_length=64)),
                ('region_2depth_name', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'mutsa_user',
            },
            managers=[
                ('objects', auths.models.MutsaUserManager()),
            ],
        ),
    ]
