# Generated by Django 5.0.7 on 2024-08-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='comment_writer',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='like_writer',
        ),
    ]
